name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write  # Docker 이미지 푸시 및 배포 시 필요할 수 있음

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build & push to prod
        if: contains(github.ref, 'develop')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/letscareer .
          docker push ${{ secrets.DOCKER_USERNAME }}/letscareer

      - name: Deploy to prod
        uses: appleboy/ssh-action@v0.1.5  # 최신 릴리스 버전을 명시하는 것이 좋음
        id: deploy-prod
        if: contains(github.ref, 'develop')
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker stop ${{ secrets.DOCKER_REPOSITORY }} || true
            sudo docker rm ${{ secrets.DOCKER_REPOSITORY }} || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/letscareer
            sudo docker run -d -p 8080:8080 -e DB_URL=${{ secrets.DB_HOST }} -e DB_USER=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} --name letscareer ${{ secrets.DOCKER_USERNAME }}/letscareer
            sudo docker image prune -f